In [1]:
filetype_groups = {
    "Dokumen & Teks": ["document", "text", "spreadsheet", "presentation", "notebook", "subtitle"],
    "Web & Kode": ["web", "code", "config", "package", "project"],
    "Media": ["image", "video", "audio", "design", "cad"],
    "GIS & Geoscience": ["gis", "geoscience"],
    "Data & Sistem": ["data", "system", "archive", "security"],
    "Lainnya": ["unknown"]
}

TOLONG BACA LANGKAH SETELAH CHECK-OUTPUT (PENCOCOKAN KLASIFIKASI FILE AWAL DENGAN PACKAGE MANUAL & ML) DI NOTEPAD

SELANJUTNYA TOLONG DIBUATKAN KELOMPOK2 DAN MULAI PEMINDAHAN FILE BERD. KOLOM SPESIFIK YANG BARU!

In [2]:
from pathlib import Path

# Definisikan base path tempat folder akan dibuat
base_path = Path(r"C:\Users\ASUS\Downloads")

# Kelompokkan file type
filetype_groups = {
    "Dokumen & Teks": ["document", "text", "spreadsheet", "presentation", "notebook", "subtitle"],
    "Web & Kode": ["web", "code", "config", "package", "project"],
    "Media": ["image", "video", "audio", "design", "cad"],
    "GIS & Geoscience": ["gis", "geoscience"],
    "Data & Sistem": ["data", "system", "archive", "security"],
    "Lainnya": ["unknown"]
}

# Buat folder dan subfolder berdasarkan struktur
for group, types in filetype_groups.items():
    for filetype in types:
        folder_path = base_path / group / filetype.capitalize()
        folder_path.mkdir(parents=True, exist_ok=True)

In [3]:
import pandas as pd

df = pd.read_csv("data_downloads_cleaned.csv")

In [4]:
df['FileType'].value_counts()

FileType
gis             2679
image           1049
document         701
data             673
unknown          547
system           375
web              336
spreadsheet      270
text             244
package          216
project          171
video             68
archive           65
audio             49
cad               33
design            26
config            17
code              16
presentation      15
geoscience        11
notebook           3
security           2
subtitle           2
Name: count, dtype: int64

In [5]:
# Buat dictionary mapping dari filetype ke group + subfolder
filetype_to_subfolder = {}

In [6]:
for group, types in filetype_groups.items():
    for filetype in types:
        filetype_to_subfolder[filetype] = {
            "main_folder": group,
            "subfolder": filetype.capitalize()
        }

In [7]:
# Fungsi bantu untuk ambil main folder
def get_main_folder(filetype):
    return filetype_to_subfolder.get(filetype, {"main_folder": "Uncategorized"})["main_folder"]

# Fungsi bantu untuk ambil subfolder
def get_subfolder(filetype):
    return filetype_to_subfolder.get(filetype, {"subfolder": filetype.capitalize()})["subfolder"]

# Tambahkan kolom ke dataframe
df["MainFolder"] = df["FileType"].apply(get_main_folder)
df["Subfolder"] = df["FileType"].apply(get_subfolder)

In [8]:
df

,FileName,FileExt,DateModified,Size_KB,Size_GB,Source,Path,SimplePath,ParentPath,FileNameClean,...,Subfolder_L3,Subfolder_L4,Subfolder_L5,Subfolder_L6,Filename,Path_Class,Path_Anomali,Path_Uniform,MainFolder,Subfolder
0,desktop,ini,2025-07-30 14:33:17.852927,0.28,0.0000,downloads,C:\Users\ASUS\Downloads\desktop.ini,Users\ASUS\Downloads\desktop.ini,C:\Users\ASUS\Downloads,Desktop,...,ASUS,Downloads,desktop.ini,unknown,desktop.ini,Downloaded,Yes,C:/Users/ASUS/Downloads/desktop.ini,Data & Sistem,System
1,GoogleDriveSetup,exe,2025-07-30 09:09:52.649726,331614.59,0.3163,downloads,C:\Users\ASUS\Downloads\GoogleDriveSetup.exe,Users\ASUS\Downloads\GoogleDriveSetup.exe,C:\Users\ASUS\Downloads,Googledrivesetup,...,ASUS,Downloads,GoogleDriveSetup.exe,unknown,GoogleDriveSetup.exe,Downloaded,Yes,C:/Users/ASUS/Downloads/GoogleDriveSetup.exe,Data & Sistem,System
2,Cover Letter_Graduate 2025 Mott MacDonald,pdf,2025-07-28 13:09:29.588192,74.41,0.0001,downloads,C:\Users\ASUS\Downloads\Cover Letter_Graduate ...,Users\ASUS\Downloads\Cover Letter_Graduate 202...,C:\Users\ASUS\Downloads,Cover Letter Graduate 2025 Mott Macdonald,...,ASUS,Downloads,Cover Letter_Graduate 2025 Mott MacDonald.pdf,unknown,Cover Letter_Graduate 2025 Mott MacDonald.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Cover Letter_Graduate ...,Dokumen & Teks,Document
3,HCML Well Sample,xlsx,2025-07-28 11:06:26.555022,275.54,0.0003,downloads,C:\Users\ASUS\Downloads\HCML Well Sample.xlsx,Users\ASUS\Downloads\HCML Well Sample.xlsx,C:\Users\ASUS\Downloads,Hcml Well Sample,...,ASUS,Downloads,HCML Well Sample.xlsx,unknown,HCML Well Sample.xlsx,Downloaded,Yes,C:/Users/ASUS/Downloads/HCML Well Sample.xlsx,Dokumen & Teks,Spreadsheet
4,Document Location Number List_Final 01_Eko (Au...,xlsx,2025-07-28 11:04:53.067396,1921.30,0.0018,downloads,C:\Users\ASUS\Downloads\Document Location Numb...,Users\ASUS\Downloads\Document Location Number ...,C:\Users\ASUS\Downloads,Document Location Number List Final 01 Eko Aut...,...,ASUS,Downloads,Document Location Number List_Final 01_Eko (Au...,unknown,Document Location Number List_Final 01_Eko (Au...,Downloaded,Yes,C:/Users/ASUS/Downloads/Document Location Numb...,Dokumen & Teks,Spreadsheet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7563,7_Penggunaan Lahan,pdf,2014-01-09 21:18:40,2045.92,0.0020,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,7 Penggunaan Lahan,...,ASUS,Downloads,Portfolio,magang PATGTL,7_Penggunaan Lahan.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document
7564,4_Gunungapi,pdf,2014-01-09 21:18:32,1533.31,0.0015,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,4 Gunungapi,...,ASUS,Downloads,Portfolio,magang PATGTL,4_Gunungapi.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document
7565,1_Kelas_Lereng,pdf,2014-01-09 21:18:28,2025.40,0.0019,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,1 Kelas Lereng,...,ASUS,Downloads,Portfolio,magang PATGTL,1_Kelas_Lereng.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document
7566,5_Pengamatan,pdf,2014-01-09 21:18:24,1617.38,0.0015,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,5 Pengamatan,...,ASUS,Downloads,Portfolio,magang PATGTL,5_Pengamatan.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document
7567,6_Curah Hujan,pdf,2014-01-09 21:18:18,1618.46,0.0015,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,6 Curah Hujan,...,ASUS,Downloads,Portfolio,magang PATGTL,6_Curah Hujan.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document

In [9]:
df["MainFolder"].value_counts()

MainFolder
GIS & Geoscience    2690
Dokumen & Teks      1235
Media               1225
Data & Sistem       1115
Web & Kode           756
Lainnya              547
Name: count, dtype: int64

In [10]:
df

,FileName,FileExt,DateModified,Size_KB,Size_GB,Source,Path,SimplePath,ParentPath,FileNameClean,...,Subfolder_L3,Subfolder_L4,Subfolder_L5,Subfolder_L6,Filename,Path_Class,Path_Anomali,Path_Uniform,MainFolder,Subfolder
0,desktop,ini,2025-07-30 14:33:17.852927,0.28,0.0000,downloads,C:\Users\ASUS\Downloads\desktop.ini,Users\ASUS\Downloads\desktop.ini,C:\Users\ASUS\Downloads,Desktop,...,ASUS,Downloads,desktop.ini,unknown,desktop.ini,Downloaded,Yes,C:/Users/ASUS/Downloads/desktop.ini,Data & Sistem,System
1,GoogleDriveSetup,exe,2025-07-30 09:09:52.649726,331614.59,0.3163,downloads,C:\Users\ASUS\Downloads\GoogleDriveSetup.exe,Users\ASUS\Downloads\GoogleDriveSetup.exe,C:\Users\ASUS\Downloads,Googledrivesetup,...,ASUS,Downloads,GoogleDriveSetup.exe,unknown,GoogleDriveSetup.exe,Downloaded,Yes,C:/Users/ASUS/Downloads/GoogleDriveSetup.exe,Data & Sistem,System
2,Cover Letter_Graduate 2025 Mott MacDonald,pdf,2025-07-28 13:09:29.588192,74.41,0.0001,downloads,C:\Users\ASUS\Downloads\Cover Letter_Graduate ...,Users\ASUS\Downloads\Cover Letter_Graduate 202...,C:\Users\ASUS\Downloads,Cover Letter Graduate 2025 Mott Macdonald,...,ASUS,Downloads,Cover Letter_Graduate 2025 Mott MacDonald.pdf,unknown,Cover Letter_Graduate 2025 Mott MacDonald.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Cover Letter_Graduate ...,Dokumen & Teks,Document
3,HCML Well Sample,xlsx,2025-07-28 11:06:26.555022,275.54,0.0003,downloads,C:\Users\ASUS\Downloads\HCML Well Sample.xlsx,Users\ASUS\Downloads\HCML Well Sample.xlsx,C:\Users\ASUS\Downloads,Hcml Well Sample,...,ASUS,Downloads,HCML Well Sample.xlsx,unknown,HCML Well Sample.xlsx,Downloaded,Yes,C:/Users/ASUS/Downloads/HCML Well Sample.xlsx,Dokumen & Teks,Spreadsheet
4,Document Location Number List_Final 01_Eko (Au...,xlsx,2025-07-28 11:04:53.067396,1921.30,0.0018,downloads,C:\Users\ASUS\Downloads\Document Location Numb...,Users\ASUS\Downloads\Document Location Number ...,C:\Users\ASUS\Downloads,Document Location Number List Final 01 Eko Aut...,...,ASUS,Downloads,Document Location Number List_Final 01_Eko (Au...,unknown,Document Location Number List_Final 01_Eko (Au...,Downloaded,Yes,C:/Users/ASUS/Downloads/Document Location Numb...,Dokumen & Teks,Spreadsheet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7563,7_Penggunaan Lahan,pdf,2014-01-09 21:18:40,2045.92,0.0020,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,7 Penggunaan Lahan,...,ASUS,Downloads,Portfolio,magang PATGTL,7_Penggunaan Lahan.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document
7564,4_Gunungapi,pdf,2014-01-09 21:18:32,1533.31,0.0015,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,4 Gunungapi,...,ASUS,Downloads,Portfolio,magang PATGTL,4_Gunungapi.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document
7565,1_Kelas_Lereng,pdf,2014-01-09 21:18:28,2025.40,0.0019,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,1 Kelas Lereng,...,ASUS,Downloads,Portfolio,magang PATGTL,1_Kelas_Lereng.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document
7566,5_Pengamatan,pdf,2014-01-09 21:18:24,1617.38,0.0015,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,5 Pengamatan,...,ASUS,Downloads,Portfolio,magang PATGTL,5_Pengamatan.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document
7567,6_Curah Hujan,pdf,2014-01-09 21:18:18,1618.46,0.0015,downloads,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,Users\ASUS\Downloads\Portfolio\magang PATGTL\D...,C:\Users\ASUS\Downloads\Portfolio\magang PATGT...,6 Curah Hujan,...,ASUS,Downloads,Portfolio,magang PATGTL,6_Curah Hujan.pdf,Downloaded,Yes,C:/Users/ASUS/Downloads/Portfolio,Dokumen & Teks,Document

In [11]:
import shutil
from pathlib import Path
import os
from tqdm import tqdm
import pandas as pd  # Tetap import jika belum ada

# 1. Path tujuan
destination_dir = Path(r"C:\Users\ASUS\OneDrive\Documents\Download-Folder-Management")

# 2. Kelompok FileType → MainFolder
filetype_groups = {
    "Dokumen & Teks": ["document", "text", "spreadsheet", "presentation", "notebook", "subtitle"],
    "Web & Kode": ["web", "code", "config", "package", "project"],
    "Media": ["image", "video", "audio", "design", "cad"],
    "GIS & Geoscience": ["gis", "geoscience"],
    "Data & Sistem": ["data", "system", "archive", "security"],
    "Lainnya": ["unknown"]
}

# ⚠️ Validasi df sudah ada dan ada kolom yang dibutuhkan
required_cols = {"Path", "FileName", "FileExt", "FileType"}
if not required_cols.issubset(df.columns):
    raise ValueError(f"DataFrame tidak memiliki kolom wajib: {required_cols - set(df.columns)}")

# 3. Mapping ke MainFolder & Subfolder
def assign_group_and_subfolder(filetype):
    if pd.isnull(filetype):
        return pd.Series(["Lainnya", "Unknown"])
    for group, types in filetype_groups.items():
        if filetype in types:
            return pd.Series([group, filetype.capitalize()])
    return pd.Series(["Lainnya", filetype.capitalize()])

df[["MainFolder", "Subfolder"]] = df["FileType"].apply(assign_group_and_subfolder)

# 4. Tentukan jalur tujuan akhir
df["DestPath"] = df.apply(
    lambda row: destination_dir / row["MainFolder"] / row["Subfolder"] / row["FileName"], axis=1
)

# 5. Buat folder tujuan jika belum ada
for folder in df["DestPath"].map(lambda x: x.parent).unique():
    folder.mkdir(parents=True, exist_ok=True)

# 6. Pindahkan file
print("🚚 Memindahkan file...")
for _, row in tqdm(df.iterrows(), total=len(df)):
    try:
        if Path(row["Path"]).exists():
            shutil.move(str(row["Path"]), str(row["DestPath"]))
    except Exception as e:
        print(f"❌ Gagal memindahkan: {row['Path']} -> {row['DestPath']} | Error: {e}")

# 7. Hapus folder kosong (di direktori awal)
downloads_dir = Path(r"C:\Users\ASUS\Downloads")
print("🧹 Menghapus folder kosong di Downloads...")
for dirpath, dirnames, filenames in os.walk(downloads_dir, topdown=False):
    path = Path(dirpath)
    try:
        if not any(path.iterdir()):
            path.rmdir()
            print(f"🧹 Folder kosong dihapus: {path}")
    except Exception as e:
        print(f"⚠️ Gagal menghapus folder: {path} | Error: {e}")

🚚 Memindahkan file...

100%|██████████| 7568/7568 [00:35<00:00, 210.95it/s]

🧹 Menghapus folder kosong di Downloads...
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\20 Original kevin wang picture style + 127 picture style tambahan\20 Original kevin wang picture style\127 Costume picture style
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\20 Original kevin wang picture style + 127 picture style tambahan\20 Original kevin wang picture style
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\20 Original kevin wang picture style + 127 picture style tambahan
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Adobe Premiere Pro Auto-Save
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Adobe Premiere Pro Captured Video\ADN
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Adobe Premiere Pro Captured Video
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\application.exe
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\archive
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\archive (3)
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\archive (4)
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\archive (9)
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Course VBA Macro Udemy
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\CV Raja Syafin Atreyu\CV_Raja
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\CV Raja Syafin Atreyu
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data & Sistem\Archive
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data & Sistem\Data
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data & Sistem\Security
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data & Sistem\System
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data & Sistem
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML\LWD\MBH-A1
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML\LWD\MDA-A1
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML\LWD\MDA-A2
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML\LWD\MDA-A3
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML\LWD\MDA-A4
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML\LWD\MDA-A5ST
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML\LWD
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML\Master Log
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Data Sand Management HCML
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Dataset Final Project Dibimbing.id
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\DJI Assistant 2(Consumer Drones Series) 2.1.36.exe
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Dokumen & Teks\Document
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Dokumen & Teks\Notebook
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Dokumen & Teks\Presentation
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Dokumen & Teks\Spreadsheet
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Dokumen & Teks\Subtitle
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Dokumen & Teks\Text
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Dokumen & Teks
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\dppw4.10.20-installer
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\drive-download-20241206T041927Z-001
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\drive-download-20241206T041945Z-001
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\drive-download-20241206T045137Z-001
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\drive-download-20250513T113736Z-1-001
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\CN
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\DE
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\ES
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\EULA
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\FR
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\IT
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\JP
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\KR
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\PT
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\RU
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res\US
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3\Res
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ele_-win-1_2_0-ea10_3
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\EU-Installset-W3.11.0.0
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\file-hcml
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Final Proyek DBB\individual_data
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Final Proyek DBB
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Folder CV - Portfolio - Cover Letter Fajri\LAMARAN KE GBPN INDONESIA
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Folder CV - Portfolio - Cover Letter Fajri
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Foxit PDF Editor-20250323T125835Z-001\Foxit PDF Editor\Foxit PDF 2024\Foxit 13
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Foxit PDF Editor-20250323T125835Z-001\Foxit PDF Editor\Foxit PDF 2024
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\GIS & Geoscience\Geoscience
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\GIS & Geoscience\Gis
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\GIS & Geoscience
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\HCML
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ISO SNI 30301-2019
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Kelas Foto Bercerita Nurum
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\kujung
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lainnya\Unknown
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lainnya
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lora-Full-Version\Lora-Full-Version\Desktop Fonts\Lora\static
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lora-Full-Version\Lora-Full-Version\Desktop Fonts\Lora
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lora-Full-Version\Lora-Full-Version\Desktop Fonts
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lora-Full-Version\Lora-Full-Version\Web Fonts\Lora
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lora-Full-Version\Lora-Full-Version\Web Fonts
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lora-Full-Version\Lora-Full-Version
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Lora-Full-Version
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\LPDP
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Media\Audio
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Media\Cad
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Media\Design
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Media\Image
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Media\Video
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\Media
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ndsu-win-1_60_1-ea34_2\res\EULA
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ndsu-win-1_60_1-ea34_2\res\STRING
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ndsu-win-1_60_1-ea34_2\res
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\ndsu-win-1_60_1-ea34_2
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\asset
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\backrupt
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\bankcrupt
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\brand health
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\carbon tax
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\csr
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\digital bank
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\digitalization
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\ecommerce
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\economic freedom
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\financial behavior
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\fintech
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\firm performance\firm performance NEW
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\firm performance
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\green economy
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\green finance
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\Human Resource Accounting
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\investment
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\islamic financial literacy
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\lack of education
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\low carbon economic
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\marketing strategy and ai
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\portfolio flows
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\poverty
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\renewable energy
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\smes
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\start up\sustainable finance
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\start up
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\strategic decision
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\sustainable finance
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\tourism and employee
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\toxic workplace
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\waqf
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset\women enterprenuer
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks\Contoh Dataset
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\Dataset Bibliometriks
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Artikel
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\asset
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\backrupt
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\bankcrupt
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\brand health
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\carbon tax
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\csr
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\digital bank
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\digitalization
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\ecommerce
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\economic freedom
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\financial behavior
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\fintech
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\firm performance\firm performance NEW
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\firm performance
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\green economy
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\green finance
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\Human Resource Accounting
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\investment
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\islamic financial literacy
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\lack of education
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\low carbon economic
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\marketing strategy and ai
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\portfolio flows
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\poverty
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\renewable energy
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\smes
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\start up\sustainable finance
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\start up
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\strategic decision
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\sustainable finance
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\tourism and employee
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\toxic workplace
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\waqf
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset\women enterprenuer
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik\Contoh Dataset
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001\November 2024_Mini Bootcamp Bibliometrik
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\November 2024_Mini Bootcamp Bibliometrik-20241123T002008Z-001
🧹 Folder kosong dihapus: C:\Users\ASUS\Downloads\openrefine-win-with-java-3.8.6\openrefine-3.8.6\licenses

In [12]:
df_check = df.copy()
df_check["FileExists"] = df_check["DestPath"].apply(lambda x: Path(x).exists())
df_check["FileSize"] = df_check["DestPath"].apply(lambda x: Path(x).stat().st_size if x.exists() else 0)
df_check[["FileName", "DestPath", "FileExists", "FileSize"]].head(10)

,FileName,DestPath,FileExists,FileSize
0,desktop,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
1,GoogleDriveSetup,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
2,Cover Letter_Graduate 2025 Mott MacDonald,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
3,HCML Well Sample,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
4,Document Location Number List_Final 01_Eko (Au...,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
5,document-engineer,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
6,notulen-30Jun25,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
7,3 5978-rkl-rpl 30Jun25,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
8,2 5978-andal 30Jun25,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0
9,4 Notulen Sutet 29junii2025_,C:\Users\ASUS\OneDrive\Documents\Download-Fold...,False,0

In [17]:
from pathlib import Path

# Folder asal
downloads_dir = Path(r"C:\Users\ASUS\Downloads")

# Ambil file tanpa ekstensi (dan bukan file tersembunyi)
files_no_ext = [f for f in downloads_dir.rglob("*") if f.is_file() and f.suffix == "" and not f.name.startswith(".")]

# Loop setiap file
for file in files_no_ext:
    base_name = file.name  # nama file tanpa ekstensi
    match = df[df["FileName"] == base_name]

    if not match.empty:
        ext = match["FileExt"].values[0]
        new_path = file.with_name(f"{file.name}.{ext}")

        # Validasi apakah file baru sudah ada
        if not new_path.exists():
            try:
                file.rename(new_path)
                print(f"✅ Rename: {file.name} -> {new_path.name}")
            except Exception as e:
                print(f"❌ Gagal rename: {file.name}, Error: {e}")
        else:
            print(f"⚠️ Sudah ada file: {new_path.name}")
    else:
        print(f"[SKIP] Tidak ditemukan ekstensi untuk: {file.name}")

✅ Rename: #Pa$$CŌ𝔻e--4123__OpeN-Setup$# -> #Pa$$CŌ𝔻e--4123__OpeN-Setup$#.7z
✅ Rename: 20 Original kevin wang picture style + 127 picture style tambahan -> 20 Original kevin wang picture style + 127 picture style tambahan.zip
✅ Rename: Activator -> Activator.zip
✅ Rename: Analisis Tuplah 1997 -> Analisis Tuplah 1997.rar
✅ Rename: archive -> archive.zip
✅ Rename: archive (1) -> archive (1).zip
✅ Rename: archive (2) -> archive (2).zip
✅ Rename: archive (3) -> archive (3).zip
✅ Rename: archive (4) -> archive (4).zip
✅ Rename: archive (5) -> archive (5).zip
✅ Rename: archive (6) -> archive (6).zip
✅ Rename: archive (7) -> archive (7).zip
✅ Rename: archive (8) -> archive (8).zip
✅ Rename: archive (9) -> archive (9).zip
✅ Rename: area kerja -> area kerja.mxd
✅ Rename: BD -> BD.zip
✅ Rename: Crack -> Crack.rar
✅ Rename: Data Dasar -> Data Dasar.zip
✅ Rename: Digitasi Peta Bentuk Lahan DIY -> Digitasi Peta Bentuk Lahan DIY.rar
✅ Rename: Digitasi Peta Curah Hujan DIY -> Digitasi Peta Curah Hujan DIY.rar
✅ Rename: Digitasi Peta GTL DIY_2022 -> Digitasi Peta GTL DIY_2022.rar
✅ Rename: drive-download-20241206T041927Z-001 -> drive-download-20241206T041927Z-001.zip
✅ Rename: drive-download-20241206T041945Z-001 -> drive-download-20241206T041945Z-001.zip
✅ Rename: drive-download-20241206T045137Z-001 -> drive-download-20241206T045137Z-001.zip
✅ Rename: drive-download-20250513T113736Z-1-001 -> drive-download-20250513T113736Z-1-001.zip
✅ Rename: Fajri Introduction for Baramulti -> Fajri Introduction for Baramulti.zip
✅ Rename: foxit 10 - 11 -> foxit 10 - 11.rar
✅ Rename: Foxit PDF Editor-20250323T125835Z-001 -> Foxit PDF Editor-20250323T125835Z-001.zip
✅ Rename: Foxit PDF Editor-20250323T125835Z-002 -> Foxit PDF Editor-20250323T125835Z-002.zip
✅ Rename: Foxit PDF Editor-20250323T125835Z-003 -> Foxit PDF Editor-20250323T125835Z-003.zip
✅ Rename: Foxit PhantomPDF Business 10 -> Foxit PhantomPDF Business 10.rar
✅ Rename: kujung -> kujung.shx
✅ Rename: Kwitansi Kak Dolin Sumba Barat -> Kwitansi Kak Dolin Sumba Barat.zip
✅ Rename: Kwitansi Kak Yefta Jayawijaya -> Kwitansi Kak Yefta Jayawijaya.zip
✅ Rename: MAC -> MAC.zip
✅ Rename: MBH -> MBH.zip
✅ Rename: MDA -> MDA.zip
✅ Rename: OneDrive_1_2-21-2025 -> OneDrive_1_2-21-2025.zip
✅ Rename: Penyelidikan Geologi Lingkungan Daerah Resapan Bopunjur, Jawa Barat (2013) -> Penyelidikan Geologi Lingkungan Daerah Resapan Bopunjur, Jawa Barat (2013).rar
✅ Rename: PERJANJIAN PINJAMAN FAJRI -> PERJANJIAN PINJAMAN FAJRI.zip
✅ Rename: rekomendasi titik pulau kai dan tual -> rekomendasi titik pulau kai dan tual.zip
✅ Rename: REQ ARIYA MDR KKPJM 1094 -> REQ ARIYA MDR KKPJM 1094.zip
✅ Rename: Scopus-Indonesian-Geology-xlsx -> Scopus-Indonesian-Geology-xlsx.zip
✅ Rename: SHP Geologi Maluku Tenggara dan Kota Tual -> SHP Geologi Maluku Tenggara dan Kota Tual.zip
✅ Rename: Sustainable Finance Research Dataset (1992-2019) -> Sustainable Finance Research Dataset (1992-2019).zip
✅ Rename: Tugas Magang Fajri -> Tugas Magang Fajri.zip
✅ Rename: Well Report for Pak Okky Yuditya (minus XX 1 ST) -> Well Report for Pak Okky Yuditya (minus XX 1 ST).zip
✅ Rename: [UPDATE] Fw_ [Request] List of Papers & Publications from HCML Personnel -> [UPDATE] Fw_ [Request] List of Papers & Publications from HCML Personnel.zip
✅ Rename: arc0000 -> arc0000.dat
✅ Rename: arc0001 -> arc0001.dat
✅ Rename: arc0002 -> arc0002.dat
✅ Rename: arc0003 -> arc0003.dat
✅ Rename: arc0004 -> arc0004.dat
✅ Rename: arc0005 -> arc0005.nit
✅ Rename: arc0006 -> arc0006.dat
✅ Rename: arc0007 -> arc0007.dat
✅ Rename: arc0008 -> arc0008.dat
✅ Rename: arc0009 -> arc0009.dat
✅ Rename: arc0010 -> arc0010.dat
✅ Rename: arc0011 -> arc0011.dat
✅ Rename: arc0012 -> arc0012.dat
✅ Rename: arc0013 -> arc0013.dat
✅ Rename: arc0014 -> arc0014.nit
✅ Rename: arc0015 -> arc0015.nit
✅ Rename: arc0016 -> arc0016.nit
✅ Rename: arc0017 -> arc0017.dat
✅ Rename: arc0018 -> arc0018.nit
✅ Rename: arc0019 -> arc0019.nit
✅ Rename: arc0020 -> arc0020.nit
✅ Rename: arc0021 -> arc0021.nit
✅ Rename: arc0022 -> arc0022.nit
✅ Rename: arc0023 -> arc0023.dat
✅ Rename: arc0024 -> arc0024.dat
✅ Rename: arc0025 -> arc0025.dat
✅ Rename: arc0026 -> arc0026.nit
✅ Rename: arc0027 -> arc0027.nit
✅ Rename: arc0028 -> arc0028.dat
✅ Rename: arc0029 -> arc0029.nit
✅ Rename: arc0030 -> arc0030.dat
✅ Rename: CD-1603-000141_win_cd -> CD-1603-000141_win_cd.xml
✅ Rename: Dashboard Sustainable Management Cluster - Fajri -> Dashboard Sustainable Management Cluster - Fajri.pbix
✅ Rename: DIY2007DISS -> DIY2007DISS.cpg
✅ Rename: DIY2007_FIX -> DIY2007_FIX.cpg
✅ Rename: EULAInfo -> EULAInfo.xml
✅ Rename: file1 -> file1.json
✅ Rename: file2 -> file2.json
✅ Rename: file3 -> file3.json
✅ Rename: file4 -> file4.json
✅ Rename: file5 -> file5.json
✅ Rename: InstallAnime -> InstallAnime.xml
✅ Rename: jetty-web -> jetty-web.xml
✅ Rename: katalog_gempa_v2 -> katalog_gempa_v2.csv
✅ Rename: LE07_L1TP_119066_20120419_20161202_01_T1 -> LE07_L1TP_119066_20120419_20161202_01_T1.xml
✅ Rename: LE07_L1TP_119066_20121012_20161129_01_T1 -> LE07_L1TP_119066_20121012_20161129_01_T1.xml
✅ Rename: LE07_L1TP_120065_20120613_20161202_01_T1 -> LE07_L1TP_120065_20120613_20161202_01_T1.xml
✅ Rename: LE07_L1TP_120065_20120901_20161128_01_T1 -> LE07_L1TP_120065_20120901_20161128_01_T1.xml
✅ Rename: licenses -> licenses.xml
✅ Rename: Marketing Channel Analysis -> Marketing Channel Analysis.pbix
✅ Rename: MDA TOP GL -> MDA TOP GL.qmd
✅ Rename: MDA_Top_GL_PSDM -> MDA_Top_GL_PSDM.dat
✅ Rename: metadata -> metadata.xml
✅ Rename: Papua Pegunungan -> Papua Pegunungan.sbn
✅ Rename: Progress Dashboard Finpro-Fajri(15-01-2025) -> Progress Dashboard Finpro-Fajri(15-01-2025).pbix
✅ Rename: ProgressAnime -> ProgressAnime.xml
✅ Rename: public_suffix_list -> public_suffix_list.dat
✅ Rename: Report Web Dashboard Development DBB -> Report Web Dashboard Development DBB.pbix
✅ Rename: SearchAnime -> SearchAnime.xml
✅ Rename: shortcuts-custom -> shortcuts-custom.json
✅ Rename: shortcuts-default -> shortcuts-default.json
✅ Rename: Sumba Barat -> Sumba Barat.dbf
✅ Rename: top GL -> top GL.qmd
✅ Rename: translation-ar -> translation-ar.json
✅ Rename: translation-bn -> translation-bn.json
✅ Rename: translation-bn_IN -> translation-bn_IN.json
✅ Rename: translation-ca -> translation-ca.json
✅ Rename: translation-ceb -> translation-ceb.json
✅ Rename: translation-cs -> translation-cs.json
✅ Rename: translation-da -> translation-da.json
✅ Rename: translation-de -> translation-de.json
✅ Rename: translation-el -> translation-el.json
✅ Rename: translation-en -> translation-en.json
✅ Rename: translation-en_GB -> translation-en_GB.json
✅ Rename: translation-es -> translation-es.json
✅ Rename: translation-eu -> translation-eu.json
✅ Rename: translation-fa -> translation-fa.json
✅ Rename: translation-fi -> translation-fi.json
✅ Rename: translation-fil -> translation-fil.json
✅ Rename: translation-fr -> translation-fr.json
✅ Rename: translation-he -> translation-he.json
✅ Rename: translation-hi -> translation-hi.json
✅ Rename: translation-hu -> translation-hu.json
✅ Rename: translation-id -> translation-id.json
✅ Rename: translation-it -> translation-it.json
✅ Rename: translation-iu -> translation-iu.json
✅ Rename: translation-ja -> translation-ja.json
✅ Rename: translation-ko -> translation-ko.json
✅ Rename: translation-ml -> translation-ml.json
✅ Rename: translation-mr -> translation-mr.json
✅ Rename: translation-nb_NO -> translation-nb_NO.json
✅ Rename: translation-nl -> translation-nl.json
✅ Rename: translation-pa -> translation-pa.json
✅ Rename: translation-pa_PK -> translation-pa_PK.json
✅ Rename: translation-pl -> translation-pl.json
✅ Rename: translation-pt -> translation-pt.json
✅ Rename: translation-pt_BR -> translation-pt_BR.json
✅ Rename: translation-pt_PT -> translation-pt_PT.json
✅ Rename: translation-ro -> translation-ro.json
✅ Rename: translation-ru -> translation-ru.json
✅ Rename: translation-sv -> translation-sv.json
✅ Rename: translation-ta -> translation-ta.json
✅ Rename: translation-tl -> translation-tl.json
✅ Rename: translation-tr -> translation-tr.json
✅ Rename: translation-uk -> translation-uk.json
✅ Rename: translation-zh -> translation-zh.json
✅ Rename: translation-zh_Hans -> translation-zh_Hans.json
✅ Rename: translation-zh_Hant -> translation-zh_Hant.json
✅ Rename: tzdb -> tzdb.dat
✅ Rename: USB_Anime -> USB_Anime.xml
✅ Rename: web -> web.xml
✅ Rename: blocked -> blocked.certs
✅ Rename: java -> java.policy
✅ Rename: api-ms-win-core-console-l1-1-0 -> api-ms-win-core-console-l1-1-0.dll
✅ Rename: api-ms-win-core-console-l1-2-0 -> api-ms-win-core-console-l1-2-0.dll
✅ Rename: api-ms-win-core-datetime-l1-1-0 -> api-ms-win-core-datetime-l1-1-0.dll
✅ Rename: api-ms-win-core-debug-l1-1-0 -> api-ms-win-core-debug-l1-1-0.dll
✅ Rename: api-ms-win-core-errorhandling-l1-1-0 -> api-ms-win-core-errorhandling-l1-1-0.dll
✅ Rename: api-ms-win-core-fibers-l1-1-0 -> api-ms-win-core-fibers-l1-1-0.dll
✅ Rename: api-ms-win-core-fibers-l1-1-1 -> api-ms-win-core-fibers-l1-1-1.dll
✅ Rename: api-ms-win-core-file-l1-1-0 -> api-ms-win-core-file-l1-1-0.dll
✅ Rename: api-ms-win-core-file-l1-2-0 -> api-ms-win-core-file-l1-2-0.dll
✅ Rename: api-ms-win-core-file-l2-1-0 -> api-ms-win-core-file-l2-1-0.dll
✅ Rename: api-ms-win-core-handle-l1-1-0 -> api-ms-win-core-handle-l1-1-0.dll
✅ Rename: api-ms-win-core-heap-l1-1-0 -> api-ms-win-core-heap-l1-1-0.dll
✅ Rename: api-ms-win-core-interlocked-l1-1-0 -> api-ms-win-core-interlocked-l1-1-0.dll
✅ Rename: api-ms-win-core-kernel32-legacy-l1-1-1 -> api-ms-win-core-kernel32-legacy-l1-1-1.dll
✅ Rename: api-ms-win-core-libraryloader-l1-1-0 -> api-ms-win-core-libraryloader-l1-1-0.dll
✅ Rename: api-ms-win-core-localization-l1-2-0 -> api-ms-win-core-localization-l1-2-0.dll
✅ Rename: api-ms-win-core-memory-l1-1-0 -> api-ms-win-core-memory-l1-1-0.dll
✅ Rename: api-ms-win-core-namedpipe-l1-1-0 -> api-ms-win-core-namedpipe-l1-1-0.dll
✅ Rename: api-ms-win-core-processenvironment-l1-1-0 -> api-ms-win-core-processenvironment-l1-1-0.dll
✅ Rename: api-ms-win-core-processthreads-l1-1-0 -> api-ms-win-core-processthreads-l1-1-0.dll
✅ Rename: api-ms-win-core-processthreads-l1-1-1 -> api-ms-win-core-processthreads-l1-1-1.dll
✅ Rename: api-ms-win-core-profile-l1-1-0 -> api-ms-win-core-profile-l1-1-0.dll
✅ Rename: api-ms-win-core-rtlsupport-l1-1-0 -> api-ms-win-core-rtlsupport-l1-1-0.dll
✅ Rename: api-ms-win-core-string-l1-1-0 -> api-ms-win-core-string-l1-1-0.dll
✅ Rename: api-ms-win-core-synch-l1-1-0 -> api-ms-win-core-synch-l1-1-0.dll
✅ Rename: api-ms-win-core-synch-l1-2-0 -> api-ms-win-core-synch-l1-2-0.dll
✅ Rename: api-ms-win-core-sysinfo-l1-1-0 -> api-ms-win-core-sysinfo-l1-1-0.dll
✅ Rename: api-ms-win-core-sysinfo-l1-2-0 -> api-ms-win-core-sysinfo-l1-2-0.dll
✅ Rename: api-ms-win-core-timezone-l1-1-0 -> api-ms-win-core-timezone-l1-1-0.dll
✅ Rename: api-ms-win-core-util-l1-1-0 -> api-ms-win-core-util-l1-1-0.dll
✅ Rename: api-ms-win-crt-conio-l1-1-0 -> api-ms-win-crt-conio-l1-1-0.dll
✅ Rename: api-ms-win-crt-convert-l1-1-0 -> api-ms-win-crt-convert-l1-1-0.dll
✅ Rename: api-ms-win-crt-environment-l1-1-0 -> api-ms-win-crt-environment-l1-1-0.dll
✅ Rename: api-ms-win-crt-filesystem-l1-1-0 -> api-ms-win-crt-filesystem-l1-1-0.dll
✅ Rename: api-ms-win-crt-heap-l1-1-0 -> api-ms-win-crt-heap-l1-1-0.dll
✅ Rename: api-ms-win-crt-locale-l1-1-0 -> api-ms-win-crt-locale-l1-1-0.dll
✅ Rename: api-ms-win-crt-math-l1-1-0 -> api-ms-win-crt-math-l1-1-0.dll
✅ Rename: api-ms-win-crt-multibyte-l1-1-0 -> api-ms-win-crt-multibyte-l1-1-0.dll
✅ Rename: api-ms-win-crt-private-l1-1-0 -> api-ms-win-crt-private-l1-1-0.dll
✅ Rename: api-ms-win-crt-process-l1-1-0 -> api-ms-win-crt-process-l1-1-0.dll
✅ Rename: api-ms-win-crt-runtime-l1-1-0 -> api-ms-win-crt-runtime-l1-1-0.dll
✅ Rename: api-ms-win-crt-stdio-l1-1-0 -> api-ms-win-crt-stdio-l1-1-0.dll
✅ Rename: api-ms-win-crt-string-l1-1-0 -> api-ms-win-crt-string-l1-1-0.dll
✅ Rename: api-ms-win-crt-time-l1-1-0 -> api-ms-win-crt-time-l1-1-0.dll
✅ Rename: api-ms-win-crt-utility-l1-1-0 -> api-ms-win-crt-utility-l1-1-0.dll
✅ Rename: Application -> Application.ini
✅ Rename: AppSettingData -> AppSettingData.ini
✅ Rename: Audacity_Installer_via_MuseHub -> Audacity_Installer_via_MuseHub.exe
✅ Rename: AUTORUN -> AUTORUN.inf
✅ Rename: awt -> awt.dll
✅ Rename: bitdefender_tsecurity -> bitdefender_tsecurity.exe
✅ Rename: CCL -> CCL.dll
✅ Rename: ChromeSetup -> ChromeSetup.exe
✅ Rename: CN1MPU -> CN1MPU.dll
✅ Rename: CN1MPU6 -> CN1MPU6.dll
✅ Rename: CN2MPU -> CN2MPU.dll
✅ Rename: CN2MPU6 -> CN2MPU6.dll
✅ Rename: cnclxml -> cnclxml.dll
✅ Rename: cnclxml6 -> cnclxml6.dll
✅ Rename: cnmpu -> cnmpu.dll
✅ Rename: cnmpu2 -> cnmpu2.dll
✅ Rename: cnmpu3 -> cnmpu3.dll
✅ Rename: cnwhdl -> cnwhdl.dll
✅ Rename: cnwhdl6 -> cnwhdl6.dll
✅ Rename: cnwidcn -> cnwidcn.exe
✅ Rename: cnwidif -> cnwidif.dll
✅ Rename: cnwidif6 -> cnwidif6.dll
✅ Rename: cnwidsd -> cnwidsd.dll
✅ Rename: cnwidsd6 -> cnwidsd6.dll
✅ Rename: cnwidss -> cnwidss.dll
✅ Rename: cnwidss6 -> cnwidss6.dll
✅ Rename: cnwiduns -> cnwiduns.dll
✅ Rename: cnwiduns6 -> cnwiduns6.dll
✅ Rename: cnwidus -> cnwidus.dll
✅ Rename: cnwidus6 -> cnwidus6.dll
✅ Rename: cnwidwus -> cnwidwus.dll
✅ Rename: cnwidwus6 -> cnwidwus6.dll
✅ Rename: cnwiius -> cnwiius.dll
✅ Rename: cnwiius6 -> cnwiius6.dll
✅ Rename: d3dcompiler_47 -> d3dcompiler_47.dll
✅ Rename: default -> default.jfc
✅ Rename: default_local -> default_local.policy
✅ Rename: default_US_export -> default_US_export.policy
✅ Rename: desktop -> desktop.ini
✅ Rename: DNFI -> DNFI.exe
✅ Rename: Docker Desktop Installer -> Docker Desktop Installer.exe
✅ Rename: dt_socket -> dt_socket.dll
✅ Rename: EC_Arabic -> EC_Arabic.txt
✅ Rename: EC_Bulgarian -> EC_Bulgarian.txt
✅ Rename: EC_Croatian -> EC_Croatian.txt
✅ Rename: EC_Czech -> EC_Czech.txt
✅ Rename: EC_Danish -> EC_Danish.txt
✅ Rename: EC_Dutch -> EC_Dutch.txt
✅ Rename: EC_Estonian -> EC_Estonian.txt
✅ Rename: EC_Finnish -> EC_Finnish.txt
✅ Rename: EC_French -> EC_French.txt
✅ Rename: EC_German -> EC_German.txt
✅ Rename: EC_Greek -> EC_Greek.txt
✅ Rename: EC_Hungarian -> EC_Hungarian.txt
✅ Rename: EC_Italian -> EC_Italian.txt
✅ Rename: EC_Latvian -> EC_Latvian.txt
✅ Rename: EC_Lithuanian -> EC_Lithuanian.txt
✅ Rename: EC_Norwegian -> EC_Norwegian.txt
✅ Rename: EC_Polish -> EC_Polish.txt
✅ Rename: EC_Portuguese -> EC_Portuguese.txt
✅ Rename: EC_Romanian -> EC_Romanian.txt
✅ Rename: EC_Russian -> EC_Russian.txt
✅ Rename: EC_Slovak -> EC_Slovak.txt
✅ Rename: EC_Slovenian -> EC_Slovenian.ini
✅ Rename: EC_Spanish -> EC_Spanish.txt
✅ Rename: EC_Swedish -> EC_Swedish.txt
✅ Rename: EC_Turkish -> EC_Turkish.ini
✅ Rename: EC_Ukrainian -> EC_Ukrainian.ini
✅ Rename: ele_-win-1_2_0-ea10_3 -> ele_-win-1_2_0-ea10_3.exe
✅ Rename: exempt_local -> exempt_local.policy
✅ Rename: FirewallSetting -> FirewallSetting.dll
✅ Rename: FirewallSetting64 -> FirewallSetting64.dll
✅ Rename: fontmanager -> fontmanager.dll
✅ Rename: freetype -> freetype.md
✅ Rename: GitHubDesktopSetup-x64 -> GitHubDesktopSetup-x64.exe
✅ Rename: GoogleDriveSetup -> GoogleDriveSetup.exe
✅ Rename: IJEREG -> IJEREG.exe
✅ Rename: IJRMF -> IJRMF.exe
✅ Rename: Install VALORANT -> Install VALORANT.exe
✅ Rename: InstallParameter -> InstallParameter.ini
✅ Rename: instrument -> instrument.dll
✅ Rename: j2gss -> j2gss.dll
✅ Rename: j2pcsc -> j2pcsc.dll
✅ Rename: j2pkcs11 -> j2pkcs11.dll
✅ Rename: jaas -> jaas.dll
✅ Rename: jabswitch -> jabswitch.exe
✅ Rename: jaccessinspector -> jaccessinspector.exe
✅ Rename: jaccesswalker -> jaccesswalker.exe
✅ Rename: jaotc -> jaotc.exe
✅ Rename: java -> java.policy
✅ Rename: javaaccessbridge -> javaaccessbridge.dll
✅ Rename: javajpeg -> javajpeg.dll
✅ Rename: javaw -> javaw.exe
✅ Rename: jawt -> jawt.lib
✅ Rename: jdatapath -> jdatapath.dll
✅ Rename: jdwp -> jdwp.dll
✅ Rename: jfr -> jfr.exe
✅ Rename: jimage -> jimage.dll
✅ Rename: jjs -> jjs.exe
✅ Rename: jli -> jli.dll
✅ Rename: jmxremote -> jmxremote.access
✅ Rename: JP_Japanese -> JP_Japanese.ini
✅ Rename: jre-8u431-windows-x64 -> jre-8u431-windows-x64.exe
✅ Rename: jrunscript -> jrunscript.exe
✅ Rename: jsound -> jsound.dll
✅ Rename: jvm -> jvm.lib
✅ Rename: keytool -> keytool.exe
✅ Rename: kinit -> kinit.exe
✅ Rename: klist -> klist.exe
✅ Rename: ktab -> ktab.exe
✅ Rename: Language -> Language.ini
✅ Rename: lcms -> lcms.md
✅ Rename: le -> le.dll
✅ Rename: macros -> macros.vm
✅ Rename: management -> management.properties
✅ Rename: management_agent -> management_agent.dll
✅ Rename: management_ext -> management_ext.dll
✅ Rename: Message -> Message.ini
✅ Rename: mlib_image -> mlib_image.dll
✅ Rename: MSETUP -> MSETUP.checksum
✅ Rename: Msetup4 -> Msetup4.exe
✅ Rename: MSetup64 -> MSetup64.exe
✅ Rename: msvcp140 -> msvcp140.dll
✅ Rename: MUI -> MUI.dll
✅ Rename: ndp462-kb3151802-web -> ndp462-kb3151802-web.exe
✅ Rename: ndsu-win-1_60_1-ea34_2 -> ndsu-win-1_60_1-ea34_2.exe
✅ Rename: net -> net.properties
✅ Rename: nio -> nio.dll
✅ Rename: openrefine -> openrefine.exe
✅ Rename: osgeo4w-setup -> osgeo4w-setup.exe
✅ Rename: pack200 -> pack200.exe
✅ Rename: Papua Pegunungan -> Papua Pegunungan.sbn
✅ Rename: PBIDesktopSetup_x64 -> PBIDesktopSetup_x64.exe
✅ Rename: PHA32 -> PHA32.exe
✅ Rename: PHA64 -> PHA64.exe
✅ Rename: Postman-win64-Setup -> Postman-win64-Setup.exe
✅ Rename: prefs -> prefs.dll
✅ Rename: refine -> refine.ini
✅ Rename: RES0001 -> RES0001.dll
✅ Rename: RES0002 -> RES0002.dll
✅ Rename: RES0005 -> RES0005.dll
✅ Rename: RES0006 -> RES0006.dll
✅ Rename: RES0007 -> RES0007.dll
✅ Rename: RES0008 -> RES0008.dll
✅ Rename: RES0009 -> RES0009.dll
✅ Rename: RES000a -> RES000a.dll
✅ Rename: RES000b -> RES000b.dll
✅ Rename: RES000c -> RES000c.dll
✅ Rename: RES000e -> RES000e.dll
✅ Rename: RES0010 -> RES0010.dll
✅ Rename: RES0011 -> RES0011.dll
✅ Rename: RES0012 -> RES0012.dll
✅ Rename: RES0013 -> RES0013.dll
✅ Rename: RES0014 -> RES0014.dll
✅ Rename: RES0015 -> RES0015.dll
✅ Rename: RES0016 -> RES0016.dll
✅ Rename: RES0018 -> RES0018.dll
✅ Rename: RES0019 -> RES0019.dll
✅ Rename: RES001a -> RES001a.dll
✅ Rename: RES001b -> RES001b.dll
✅ Rename: RES001d -> RES001d.dll
✅ Rename: RES001e -> RES001e.dll
✅ Rename: RES001f -> RES001f.dll
✅ Rename: RES0021 -> RES0021.dll
✅ Rename: RES0022 -> RES0022.dll
✅ Rename: RES0024 -> RES0024.dll
✅ Rename: RES0025 -> RES0025.dll
✅ Rename: RES0026 -> RES0026.dll
✅ Rename: RES0027 -> RES0027.dll
✅ Rename: RES002a -> RES002a.dll
✅ Rename: RES0104 -> RES0104.dll
✅ Rename: RES0204 -> RES0204.dll
✅ Rename: rmi -> rmi.dll
✅ Rename: rmid -> rmid.exe
✅ Rename: rmiregistry -> rmiregistry.exe
✅ Rename: schema -> schema.ini
✅ Rename: Setup -> Setup.ini
✅ Rename: setuprsc -> setuprsc.dll
✅ Rename: smenu -> smenu.ini
✅ Rename: splashscreen -> splashscreen.dll
✅ Rename: sspi_bridge -> sspi_bridge.dll
✅ Rename: sunec -> sunec.dll
✅ Rename: sunmscapi -> sunmscapi.dll
✅ Rename: tcmd1103x32_64 -> tcmd1103x32_64.exe
✅ Rename: TeamsSetupx64_s_8DC8F42016FB404-1-0_c_w_ -> TeamsSetupx64_s_8DC8F42016FB404-1-0_c_w_.exe
✅ Rename: Telegram -> Telegram.exe
✅ Rename: TestPrint -> TestPrint.dll
✅ Rename: TestPrint64 -> TestPrint64.dll
✅ Rename: ucrtbase -> ucrtbase.dll
✅ Rename: uinstrsc -> uinstrsc.dll
✅ Rename: UNINST -> UNINST.exe
✅ Rename: unpack -> unpack.dll
✅ Rename: unpack200 -> unpack200.exe
✅ Rename: UnZip -> UnZip.dll
✅ Rename: UnZip64 -> UnZip64.dll
✅ Rename: UnZipCs -> UnZipCs.exe
✅ Rename: Updater -> Updater.exe
✅ Rename: US_English -> US_English.ini
✅ Rename: US_Indonesian -> US_Indonesian.ini
✅ Rename: US_Korean -> US_Korean.ini
✅ Rename: US_SimplifiedChinese -> US_SimplifiedChinese.ini
✅ Rename: US_Thai -> US_Thai.ini
✅ Rename: US_TraditionalChinese -> US_TraditionalChinese.ini
✅ Rename: US_Vietnamese -> US_Vietnamese.ini
✅ Rename: vcruntime140 -> vcruntime140.dll
✅ Rename: vcruntime140_1 -> vcruntime140_1.dll
✅ Rename: verify -> verify.dll
✅ Rename: VOSviewer -> VOSviewer.exe
✅ Rename: w2k_lsa_auth -> w2k_lsa_auth.dll
✅ Rename: win-e470-1_3-n_mcd -> win-e470-1_3-n_mcd.exe
✅ Rename: windowsaccessbridge-64 -> windowsaccessbridge-64.dll
✅ Rename: winrar-x64-591 -> winrar-x64-591.exe